server:
  port: 8081
  host: localhost

spring:
  datasource:
    url: jdbc:h2:mem:benDb
    username: ben
    password: benit
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method